
builds:
  # You can have multiple builds defined as a yaml list
  -
    main: ./cmd/manager/main.go
    # flags:
    #    - -race
    # Custom ldflags templates.
    # Default is `-s -w -X main.version={{.Version}} -X main.commit={{.ShortCommit}} -X main.date={{.Date}} -X main.builtBy=goreleaser`.
    # ldflags:
    #  - -X github.com/keikoproj/addon-manager/pkg/version.buildDate=${BUILD} 
    #  - -X github.com/keikoproj/addon-manager/pkg/version.gitCommit=${COMMIT} 
    #  - -X github.com/keikoproj/addon-manager/pkg/version.version=${VERSION} 

    # Custom environment variables to be set during the builds.
    # Default is empty.
    env:
      - CGO_ENABLED=0
    
    # goarch:
    #   - linux/amd64
    #   - darwin/amd64
    #   - windows/amd64

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
archives:
- replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
