before:
  hooks:
    - chmod a+x .goreleaserHook.sh
    - sh ./.goreleaserHook.sh
builds:
  - 
    id: 'manager'
    main: ./cmd/manager/main.go
    binary: addon-manager
  
    ldflags:
      - -X github.com/keikoproj/addon-manager/pkg/version.buildDate={{.Env.BUILD}}
      - -X github.com/keikoproj/addon-manager/pkg/version.gitCommit={{.Env.COMMIT}}
      - -X github.com/keikoproj/addon-manager/pkg/version.version={{.Env.VERSION}}

    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    
    goos:
      - linux 

    goarch:
      - amd64

  - 
    id: 'addonctl'
    binary: addonctl
    main: ./cmd/addonctl/main.go
  
    ldflags:
      - -X github.com/keikoproj/addon-manager/pkg/version.buildDate={{.Env.BUILD}} 
      - -X github.com/keikoproj/addon-manager/pkg/version.gitCommit={{.Env.COMMIT}} 
      - -X github.com/keikoproj/addon-manager/pkg/version.version={{.Env.VERSION}}

    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    
    goos:
      - linux 

    goarch:
      - amd64
    
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
