
before:
  hooks:
    - go mod download

builds:
  -
    id: 'manager'
    main: ./main.go
    binary: manager

    ldflags:
      - -X github.com/keikoproj/addon-manager/pkg/version.BuildDate={{.Timestamp}}
      - -X github.com/keikoproj/addon-manager/pkg/version.GitCommit={{.ShortCommit}}
      - -X github.com/keikoproj/addon-manager/pkg/version.Version={{.Version}}

    env:
      - CGO_ENABLED=0
      - GO111MODULE=on

    goos:
      - linux

    goarch:
      - amd64

  -
    id: 'addonctl'
    binary: addonctl
    main: ./cmd/addonctl/main.go

    ldflags:
      - -X github.com/keikoproj/addon-manager/pkg/version.BuildDate={{.Timestamp}}
      - -X github.com/keikoproj/addon-manager/pkg/version.GitCommit={{.ShortCommit}}
      - -X github.com/keikoproj/addon-manager/pkg/version.Version={{.Version}}

    env:
      - CGO_ENABLED=0
      - GO111MODULE=on

    goos:
      - linux

    goarch:
      - amd64

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-snapshot-{{ .ShortCommit }}"

dockers:
  - goos: linux
    goarch: amd64
    goarm: ''
    binaries:
      - manager
    builds:
      - manager
    skip_push: false
    image_templates:
      - "keikoproj/addon-manager:{{ .Version }}"
      - "keikoproj/addon-manager:latest"
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--build-arg=SOURCE_BINARY=manager"
