
before:
  hooks:
    - go mod tidy
    - go mod download
    - go generate ./...
    - go fmt ./...
    - go vet ./...
builds:
  -
    id: 'manager'
    main: ./main.go
    binary: manager

    ldflags:
      - -X github.com/keikoproj/addon-manager/pkg/version.BuildDate={{.Date}}
      - -X github.com/keikoproj/addon-manager/pkg/version.GitCommit={{.ShortCommit}}
      - -X github.com/keikoproj/addon-manager/pkg/version.Version=v{{.Version}}

    env:
      - CGO_ENABLED=0
      - GO111MODULE=on

    goos:
      - linux

    goarch:
      - amd64
      - arm64

  -
    id: 'addonctl'
    binary: addonctl
    main: ./cmd/addonctl/main.go

    ldflags:
      - -X github.com/keikoproj/addon-manager/pkg/version.BuildDate={{.Date}}
      - -X github.com/keikoproj/addon-manager/pkg/version.GitCommit={{.ShortCommit}}
      - -X github.com/keikoproj/addon-manager/pkg/version.Version=v{{.Version}}

    env:
      - CGO_ENABLED=0
      - GO111MODULE=on

    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
archives:
  - id: addonctl-archive
    builds:
      - addonctl
    name_template: "{{ .ProjectName }}_{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}"
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
changelog:
  skip: true
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Major }}.{{ .Minor }}-dev-{{ .ShortCommit }}"

dockers:
  - goos: linux
    goarch: amd64
    goarm: ''
    skip_push: false
    use_buildx: true
    ids:
      - manager
    image_templates:
      - "keikoproj/addon-manager:v{{ .Version }}-amd64"
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--platform=linux/amd64"
    extra_files:
      - go.mod
      - go.sum
  - goos: linux
    goarch: arm64
    goarm: ''
    skip_push: false
    use_buildx: true
    ids:
      - manager
    image_templates:
      - "keikoproj/addon-manager:v{{ .Version }}-arm64"
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--platform=linux/arm64"
    extra_files:
      - go.mod
      - go.sum
docker_manifests:
  - name_template: "keikoproj/addon-manager:v{{ .Version }}"
    image_templates:
      - "keikoproj/addon-manager:v{{ .Version }}-amd64"
      - "keikoproj/addon-manager:v{{ .Version }}-arm64"
