
builds:
  # You can have multiple builds defined as a yaml list
  - 
    id: 'manager'
    main: ./cmd/manager/main.go
    binary: addon-manager
  
  # flags:
  #    - -race
  # Custom ldflags templates.
  # Default is `-s -w -X main.version={{.Version}} -X main.commit={{.ShortCommit}} -X main.date={{.Date}} -X main.builtBy=goreleaser`.
    ldflags:
      - -X github.com/keikoproj/addon-manager/pkg/version.buildDate=${BUILD} 
      - -X github.com/keikoproj/addon-manager/pkg/version.gitCommit=${COMMIT} 
      - -X github.com/keikoproj/addon-manager/pkg/version.version=${VERSION} 

    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    
    goos:
      - linux 

    goarch:
      - amd64

  # You can have multiple builds defined as a yaml list
  - 
    id: 'addonctl'
    binary: addonctl
    main: ./cmd/addonctl/main.go
  
  # flags:
  #    - -race
  # Custom ldflags templates.
  # Default is `-s -w -X main.version={{.Version}} -X main.commit={{.ShortCommit}} -X main.date={{.Date}} -X main.builtBy=goreleaser`.
    ldflags:
      - -X github.com/keikoproj/addon-manager/pkg/version.buildDate=${BUILD} 
      - -X github.com/keikoproj/addon-manager/pkg/version.gitCommit=${COMMIT} 
      - -X github.com/keikoproj/addon-manager/pkg/version.version=${VERSION} 

    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    
    goos:
      - linux 

    goarch:
      - amd64
    
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
