// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// AddonListerExpansion allows custom methods to be added to
// AddonLister.
type AddonListerExpansion interface{}

// AddonNamespaceListerExpansion allows custom methods to be added to
// AddonNamespaceLister.
type AddonNamespaceListerExpansion interface{}
