// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/keikoproj/addon-manager/pkg/client/clientset/versioned/typed/addon/v1alpha1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeAddonmgrV1alpha1 struct {
	*testing.Fake
}

func (c *FakeAddonmgrV1alpha1) Addons(namespace string) v1alpha1.AddonInterface {
	return &FakeAddons{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeAddonmgrV1alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
