name: unit-test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: |
        make docker-build

    - name: Test
      run: |
        make test
    
    - name: Upload to Codecov
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.txt
